### ISSUE TITLE
can't run private commands

### ISSUE THREAD

**Issue by remyferre** [remyferre/octokit-issues#10]
<a href=https://github.com/mwotton>  <img src=https://avatars.githubusercontent.com/u/68482?v=3 align=left width=48 height=48 hspace=10></img></a> **Issue by [mwotton](https://github.com/mwotton)**
_26/04/2011 at 02:01PM_

 ---- 

I'm trying to create a repo programmatically and not having much luck:

>> o=Octokit::Client.new :login => 'mwotton', :token => token
#<Octokit::Client:0xa54743c @adapter=:net_http, @endpoint="https://github.com/", @format=:json, @login="mwotton", @password=nil, @proxy=nil, @token="somethingelse", @oauth_token=nil, @user_agent="Octokit Ruby Gem 0.6.1", @version=2>
>> o.create_repository "ffff"
NoMethodError: undefined method `bytesize' for {:name=>"ffff"}:Hash
	from /home/mwotton/.rvm/rubies/ruby-1.9.2-rc2/lib/ruby/1.9.1/net/http.rb:1727:in `send_request_with_body'
	from /home/mwotton/.rvm/rubies/ruby-1.9.2-rc2/lib/ruby/1.9.1/net/http.rb:1716:in `exec'
	from /home/mwotton/.rvm/rubies/ruby-1.9.2-rc2/lib/ruby/1.9.1/net/http.rb:1181:in `transport_request'
	from /home/mwotton/.rvm/rubies/ruby-1.9.2-rc2/lib/ruby/1.9.1/net/http.rb:1169:in `request'
	from /home/mwotton/.rvm/rubies/ruby-1.9.2-rc2/lib/ruby/1.9.1/net/http.rb:1162:in `block in request'
	from /home/mwotton/.rvm/rubies/ruby-1.9.2-rc2/lib/ruby/1.9.1/net/http.rb:627:in `start'
	from /home/mwotton/.rvm/rubies/ruby-1.9.2-rc2/lib/ruby/1.9.1/net/http.rb:1160:in `request'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/faraday-0.6.1/lib/faraday/adapter/net_http.rb:51:in `call'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/faraday-0.6.1/lib/faraday/response.rb:8:in `call'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/faraday-0.6.1/lib/faraday/response.rb:8:in `call'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/faraday-0.6.1/lib/faraday/response.rb:8:in `call'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/faraday-0.6.1/lib/faraday/request.rb:88:in `run'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/faraday-0.6.1/lib/faraday/request.rb:28:in `run'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/faraday-0.6.1/lib/faraday/connection.rb:170:in `run_request'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/faraday-0.6.1/lib/faraday/connection.rb:69:in `post'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/octokit-0.6.1/lib/octokit/client/request.rb:23:in `request'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/octokit-0.6.1/lib/octokit/client/request.rb:9:in `post'
	from /home/mwotton/.rvm/gems/ruby-1.9.2-rc2/gems/octokit-0.6.1/lib/octokit/client/repositories.rb:40:in `create_repository'
	from (irb):18
	from /home/mwotton/.rvm/rubies/ruby-1.9.2-rc2/bin/irb:17:in `<main>'>> 

Am I just calling create_repo incorrectly?

**Comment by remyferre** [comment]
<a href=https://github.com/pengwynn>  <img src=https://avatars.githubusercontent.com/u/865?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [pengwynn](https://github.com/pengwynn)**
_26/04/2011 at 05:04PM_


 ---- 


Looks like the fix has been applied to master, waiting on the next release. @sferik, anything holding up a new version?

**Comment by remyferre** [comment]
<a href=https://github.com/sferik>  <img src=https://avatars.githubusercontent.com/u/10308?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [sferik](https://github.com/sferik)**
_26/04/2011 at 05:15PM_


 ---- 


I just pushed version 0.6.2. Give that a try.

**Comment by remyferre** [comment]
<a href=https://github.com/mwotton>  <img src=https://avatars.githubusercontent.com/u/68482?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [mwotton](https://github.com/mwotton)**
_26/04/2011 at 10:18PM_


 ---- 


I was testing master - just tried again with 0.6.2 and got the same result. Using ruby 1.9.2, tested on mac and ubuntu.

**Comment by remyferre** [comment]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [jamtur01](https://github.com/jamtur01)**
_04/05/2011 at 08:30PM_


 ---- 


I've got the same issue on 0.6.2.

**Comment by remyferre** [comment]
<a href=https://github.com/pengwynn>  <img src=https://avatars.githubusercontent.com/u/865?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [pengwynn](https://github.com/pengwynn)**
_05/05/2011 at 01:26PM_


 ---- 


I just applied a patch from @laserlemon. Can you give it a whirl?

**Comment by remyferre** [comment]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [jamtur01](https://github.com/jamtur01)**
_05/05/2011 at 03:12PM_


 ---- 


That fixes it for me.

**Comment by remyferre** [comment]
<a href=https://github.com/pengwynn>  <img src=https://avatars.githubusercontent.com/u/865?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [pengwynn](https://github.com/pengwynn)**
_05/05/2011 at 03:34PM_


 ---- 


Sweet, closing again.

**Comment by remyferre** [comment]
<a href=https://github.com/sferik>  <img src=https://avatars.githubusercontent.com/u/10308?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [sferik](https://github.com/sferik)**
_05/05/2011 at 04:40PM_


 ---- 


I'm about to push a release that includes this patch.

**Comment by remyferre** [comment]
<a href=https://github.com/mwotton>  <img src=https://avatars.githubusercontent.com/u/68482?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [mwotton](https://github.com/mwotton)**
_06/05/2011 at 06:00AM_


 ---- 


works a treat, thanks.

**Comment by remyferre** [comment]
_The original issue was closed on 05/05/2011 at 03:34PM_

**Comment by laserlemon** [comment]
:tada:
